packages:
  - "packages/*"
  - "demo"

allowBuilds:
  esbuild: false
  workerd: false

# Define a catalog of version ranges.
catalog:
  ziko: ^2.0.0-beta.8
  vite: ^8.2.1

minimumReleaseAgeExclude:
  - ziko@2.0.0-beta.8
