packages:
  - "packages/*"
  - "packages/integrations/*"
  - "demos/*"

allowBuilds:
  esbuild: false
  preact: false
  workerd: false

# Define a catalog of version ranges.
catalog:
  ziko: latest
  vite: ^8.2.1

minimumReleaseAgeExclude:
  - ziko@2.0.0-beta.16.2
